config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_list.urls", namespace="todo_list")),
]

todo_list/urls.py
from django.urls import path

from todo_list.views import (
    TaskListView,
    TagListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    change_complete_status,
)

urlpatterns = [
    path(
        "",
        TaskListView.as_view(),
        name="tasks-list",
    ),
    path(
        "create/",
        TaskCreateView.as_view(),
        name="tasks-create",
    ),
    path(
        "<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="tasks-update",
    ),
    path(
        "<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="tasks-delete",
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tags-list",
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tags-create",
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tags-update",
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tags-delete",
    ),
    path(
        "change_complete_status/<int:pk>/",
        change_complete_status,
        name="change-complete-status",
    ),
]

app_name = "todo-list"

todo_list/models.py
from django.db import models
from django.utils import timezone


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    creation_time = models.DateTimeField(default=timezone.now)
    deadline = models.DateTimeField(blank=True, null=True)
    complete = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    def __str__(self):
        return f" Task: {self.content}"

todo_list/forms.py
from django import forms

from todo_list.models import Task, Tag


class TaksCreationForm(forms.Form):
    class Meta:
        model = Task
        fields = "__all__"


class TagsCreationForm(forms.Form):
    class Meta:
        model = Tag
        fields = "__all__"

todo_list/views.py
from django.http import HttpRequest
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from todo_list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo-list:tasks-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo-list:tasks-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo-list:tasks-list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo-list:tags-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo-list:tags-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo-list:tags-list")


def change_complete_status(request: HttpRequest, pk: int):
    task = Task.objects.get(id=pk)
    task.complete = not task.complete
    task.save()
    return redirect(request.META["HTTP_REFERER"])

templates/Base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
        crossorigin="anonymous">
  {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <title>Todo-list</title>
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-10 ">
      {% block content %}{% endblock %}
    </div>
  </div>
</div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Todo-list</title>
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-10 ">
      {% block content %}{% endblock %}
    </div>
  </div>
</div>
</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
    <li class="list-group-item block-on-sidebar"><a class="nav-link" href="{% url 'todo_list:tasks-list' %}">Home</a></li>
    <li class="list-group-item block-on-sidebar"><a class="nav-link" href="{% url 'todo_list:tags-list'%}">Tags</a></li>
</ul>

templates/todo_list/tag_confirm_delete.html
{% extends "Base.html" %}

{% block content %}
  <h1>Delete this tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/tag_form.html
{% extends "Base.html" %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/tag_list.html
{% extends "Base.html" %}


{% block content %}
  <h1>
    Tags List
    <a href="{% url 'todo_list:tags-create' %}" class="btn btn-primary link-to-page">
      Add
    </a>
  </h1>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a href="{% url 'todo_list:tags-update' pk=tag.id %}" class="btn btn-secondary">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'todo_list:tags-delete' pk=tag.id %}" class="btn btn-secondary">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
      <p>There are no Tags!</p>
  {% endif %}
{% endblock %}

templates/todo_list/tags_list.html
{% extends "Base.html" %}


{% block content %}
  <h1>
    Tags List
    <a href="{% url 'todo_list:tags-create' %}" class="btn btn-primary">
      Create
    </a>
  </h1>
  {% if tags_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tags_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a href="{% url 'todo_list:tags-update' pk=tag.id %}">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'todo_list:tags-delete' pk=tag.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
      <p>There are no Tags!</p>
  {% endif %}
{% endblock %}

templates/todo_list/task_confirm_delete.html
{% extends "Base.html" %}

{% block content %}
  <h1>Delete this task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/task_form.html
{% extends "Base.html" %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/task_list.html
{% extends "Base.html" %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url 'todo_list:tasks-create' %}" class="btn btn-primary link-to-page">
      Add task
    </a>
  </h1>
  {% if task_list %}
    {% for task in task_list %}
      <strong>
        {{ task.content }}
        {% if task.complete is True %}
        <p style="color: darkgreen">
          Done
        </p>
        {% else %}
        <p style="color: red">
          Not done
        </p>
        {% endif %}
      </strong>
      {% if task.complete is True %}
      <a href="{% url 'todo_list:change-complete-status' pk=task.id %}" class="btn btn-danger link-to-page">
        Undo
      </a>
      {% else %}
      <a href="{% url 'todo_list:change-complete-status' pk=task.id %}" class="btn btn-success link-to-page">
        Complete
      </a>
      {% endif %}
      <br>
      <p>Created at: {{ task.creation_time }}</p>
      <br>
      {% if task.deadline %}
        <p style="color: darkred">Deadline: {{ task.creation_time }}</p>
      {% endif %}
      <p>Tags:
      {% for tag in task.tags.all %}
        {{ tag.name }}
      {% endfor %}
      <a href="{% url 'todo_list:tasks-update' pk=task.id %}">
        Update
      </a>
      <a href="{% url 'todo_list:tasks-delete' pk=task.id %}">
        Delete
      </a>
      </p>
      <hr/>
    {% endfor %}
    {% else %}
      <p>There are no Tasks!</p>
  {% endif %}
{% endblock %}